In [1]:
%pylab inline
from sklearn.datasets import fetch_20newsgroups
news=fetch_20newsgroups()
print(type(news.data),type(news.target),type(news.target_names))

Populating the interactive namespace from numpy and matplotlib


<class 'list'> <class 'numpy.ndarray'> <class 'list'>


In [2]:
print (news.target_names)
print (len(news.data))
print (len(news.target))
print (news.data[0])
print (news.target[0], news.target_names[news.target[0]])

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
11314
11314
From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever inf

In [4]:
split_perc=0.75
split_size=int(len(news.data)*split_perc)
X_train=news.data[:split_size]
X_test=news.data[split_size:]
y_train=news.data[:split_size]
y_test=news.data[split_size:]

In [6]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer, HashingVectorizer, CountVectorizer


In [8]:
from sklearn.cross_validation import cross_val_score, KFold
from scipy.stats import sem

def evaluate_cross_validation(clf, X, y, K):
    # create a k-fold croos validation iterator of k=5 folds
    cv = KFold(len(y), K, shuffle=True, random_state=0)
    # by default the score used is the one returned by score method of the estimator (accuracy)
    scores = cross_val_score(clf, X, y, cv=cv)
    print (scores)
    print (("Mean score: {0:.3f} (+/-{1:.3f})").format(
        np.mean(scores), sem(scores)))

C:\Program Files (x86)\Python\New folder\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [11]:
clf_1 = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', MultinomialNB()),
])
clf_2 = Pipeline([
    ('vect', HashingVectorizer(non_negative=True)),
    ('clf', MultinomialNB()),
])
clf_3 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', MultinomialNB()),
])

In [12]:
clfs=[clf_1,clf_2,clf_3]
for clf in clfs:
    evaluate_cross_validation(clf,news.data,news.target,5)

[ 0.82589483  0.83473266  0.8272205   0.84136103  0.83377542]
Mean score: 0.833 (+/-0.003)


C:\Program Files (x86)\Python\New folder\lib\site-packages\sklearn\feature_extraction\hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
C:\Program Files (x86)\Python\New folder\lib\site-packages\sklearn\feature_extraction\hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
C:\Program Files (x86)\Python\New folder\lib\site-packages\sklearn\feature_extraction\hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
C:\Program Files (x86)\Python\New folder\lib\site-packages\sklearn\feature_extraction\hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in vers

[ 0.76358816  0.72337605  0.72293416  0.74370305  0.74977896]
Mean score: 0.741 (+/-0.008)
[ 0.84975696  0.83517455  0.82545294  0.83870968  0.84615385]
Mean score: 0.839 (+/-0.004)


In [20]:
def get_stop_words():
    result = set()
    for line in open('stopwords_en.txt', 'r').readlines():
        result.add(line.strip())
    return result

In [21]:
stop_words = get_stop_words()
print (stop_words)

{'have', 'among', 'top', 'former', 'into', 'she', 'wherein', 'why', 'either', 'by', 'always', 'could', 'whence', 'between', 'when', 'full', 'might', 'no', 'through', 'due', 'move', 'everywhere', 'still', 'there', 'one', 'these', 'yourselves', 'himself', 'else', 'fire', 'upon', 'than', 'hereby', 'five', 'themselves', 'two', 'without', 'though', 'done', 'every', 'same', 'so', 'whereafter', 'beforehand', 'an', 'seem', 'some', 'mill', 'latterly', 'thin', 'hasnt', 'been', 'their', 'another', 'give', 'we', 'more', 'therein', 'therefore', 'if', 'amoungst', 'part', 'serious', 'within', 'although', 'anywhere', 'below', 'not', 'then', 'because', 'somewhere', 'whereby', 'bill', 'many', 'call', 'about', 'in', 'eleven', 'per', 'show', 'much', 'thus', 'whereas', 'has', 'is', 'four', 'do', 'hers', 'it', 'of', 'other', 'seems', 'something', 'became', 'thick', 'towards', 'at', 'anyone', 'three', 'such', 'six', 'sometime', 'cry', 'whereupon', 'from', 'take', 'had', 'inc', 'what', 'nine', 'anything', 'be

In [35]:
clf_5 = Pipeline([
    ('vect', TfidfVectorizer(
                stop_words=stop_words)),('clf', MultinomialNB())])
evaluate_cross_validation(clf_5, news.data, news.target, 5)

[ 0.88643394  0.88068935  0.87052585  0.87671233  0.88107869]
Mean score: 0.879 (+/-0.003)


In [36]:
clf_6 = Pipeline([
    ('vect', TfidfVectorizer(
                stop_words=stop_words)),('clf', MultinomialNB(alpha=0.01))])
evaluate_cross_validation(clf_5, news.data, news.target, 5)

[ 0.88643394  0.88068935  0.87052585  0.87671233  0.88107869]
Mean score: 0.879 (+/-0.003)


In [38]:
from sklearn import metrics

def train_and_evaluate(clf, X_train, X_test, y_train, y_test):
    
    clf.fit(X_train, y_train)
    
    print ("Accuracy on training set:")
    print (clf.score(X_train, y_train))
    print ("Accuracy on testing set:")
    print (clf.score(X_test, y_test))
    
    y_pred = clf.predict(X_test)
    
    print ("Classification Report:")
    print (metrics.classification_report(y_test, y_pred))
    print ("Confusion Matrix:")
    print (metrics.confusion_matrix(y_test, y_pred))

In [39]:
train_and_evaluate(clf_6, X_train, X_test, y_train, y_test)

MemoryError: 